apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: lahirisan80/mock_payment_service
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
...
apiVersion: v1
kind: service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: NodePort
  ports:
    port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selectors:
    app: paymentservice
